package stateMachine;

public enum AttrType {
   EQ, NE, GTE, GT, LTE, LT, PLUS_EQUAL, MINUS_EQUAL, DIV_EQUAL, MULT_EQUAL, SUBTRACT, ADD, MULTIPLY, DIVIDE, 
   L_SQUARE_BR, R_SQUARE_BR, L_CURL_BR, R_CURL_BR, L_CURL_BRACE, R_CURL_BRACE, R_ARROW, COMMA, SEMI_COLON,
   AND, OR, NOT, EQOR, INVERT, EQUALITY, INCREMENT, DECREMENT, COLON, UNKNOWN
 }
