package stateMachine;

public enum OpType {
	 ADD, SUBTRACT, MULTIPLY, DIVIDE, ADD_TO_VAR, MULT_ADD, ASSIGN_VAR, BRANCH_FUNC, BRANCH_PROB,
	 ASSIGN_ADD_VAR, ASSIGN_SUB_VAR, ASSIGN_MULT_VAR, ASSIGN_DIV_VAR, BRANCH_VAR, RETURN, PRINT,
	 OR, NOT, AND, EQOR, LTE, LT, GTE, GT, EQUALITY, OBJECTIVE, INCREMENT, DECREMENT, CONST, PLOT, NULL
}
